module.exports = function(grunt) {
  require('jit-grunt')(grunt);

  grunt.initConfig({
    less: {
      development: {
        options: {
          compress: false,
          yuicompress: true,
          optimization: 2,
          sourceMap: true,
        },
        files: {
          "css/style.css": "css/less/style.less", // destination file and source file
          "css/layout.css": "css/less/layout.less", // destination file and source file
          "css/forms.css": "css/less/forms.less", // destination file and source file
          "css/print.css": "css/less/print.less", // destination file and source file
        },
        banner: "Generated by Grunt / Less."
      },
      production: {
        options: {
          compress: true,
          yuicompress: true,
          optimization: 2,
          sourceMap: false,
        },
        files: {
          "css/style.css": "css/less/style.less", // destination file and source file
          "css/layout.css": "css/less/layout.less", // destination file and source file
          "css/forms.css": "css/less/forms.less", // destination file and source file
          "css/print.css": "css/less/print.less", // destination file and source file
        },
        banner: "Generated by Grunt / Less."
      }

    },
    watch: {
      styles: {
        files: ['css/**/*.less'], // which files to watch
        tasks: ['less'],
        options: {
          nospawn: true
        }
      }
    }
  });
  grunt.registerTask('default', ['less:development', 'watch']);
};